# Generated by Django 6.0.3 on 2026-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
