# Generated by Django 6.0.3 on 2026-04-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_created_at'),
        ('exams', '0009_question_subject'),
        ('subjects', '0002_remove_subject_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classes.class'),
        ),
    ]
