# Generated by Django 6.0.3 on 2026-03-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_add_created_at_to_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
