# Generated by Django 6.0.3 on 2026-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='class_avatars/'),
        ),
    ]
