# Generated by Django 6.0.3 on 2026-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('auto', 'Chấm tự động'), ('approved', 'Đã phê duyệt'), ('rejected', 'Bị từ chối')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
