# Generated by Django 6.0.3 on 2026-03-10 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0005_exam_max_attempts'),
        ('subjects', '0002_remove_subject_class_obj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('user_satisfaction_score', models.FloatField(blank=True, help_text='Điểm hài lòng của user (1-5)', null=True)),
                ('most_asked_questions', models.JSONField(blank=True, default=list, help_text='Top 10 câu hỏi được hỏi nhiều nhất')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Regex pattern để match câu hỏi của user', max_length=500)),
                ('response', models.TextField(help_text='Câu trả lời của bot')),
                ('category', models.CharField(choices=[('greeting', 'Chào hỏi'), ('help', 'Trợ giúp'), ('exam', 'Bài thi'), ('study', 'Học tập'), ('technical', 'Kỹ thuật'), ('account', 'Tài khoản'), ('other', 'Khác')], default='other', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Độ ưu tiên, số càng cao càng ưu tiên')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quick_replies', models.JSONField(blank=True, default=list, help_text='List of quick reply buttons')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_page', models.CharField(blank=True, max_length=255, null=True)),
                ('current_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='exams.exam')),
                ('current_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_type', models.CharField(blank=True, help_text='Loại response: rule_based, ai_generated, quick_reply', max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Độ tin cậy của AI response (0-1)', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
