# Generated by Django 6.0.3 on 2026-04-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_created_at'),
        ('subjects', '0002_remove_subject_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.class'),
        ),
    ]
